import type { Metadata } from 'next'
import { Theme } from '@radix-ui/themes'
import '@radix-ui/themes/styles.css'

export const metadata: Metadata = {
  title: 'ラブカハートカウンター',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja">
      <body style={{ margin: '0px', padding: '0px' }}>
        <Theme>{children}</Theme>
      </body>
    </html>
  )
}
